application: mosaygenerator
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /.*
  script: index.py

libraries:
- name: PIL
  version: latest
